-- begin BPM_STENCIL_SET
create unique index IDX_BPM_BPM_STENCIL_SET_UNIQ_NAME on BPM_STENCIL_SET (NAME);
create unique index IDX_BPM_BPM_STENCIL_SET_UNIQ_JSON_DATA on BPM_STENCIL_SET (JSON_DATA)^
-- end BPM_STENCIL_SET
